name: Run Go Tests on Master

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Run Tests
        run: go test go.codycody31.dev/nano64 -v -cover
